
#pragma once

#define BBKEY_PATROLPOS TEXT("PatrolPos")
#define BBKEY_TARGET TEXT("Target")
#define BBKEY_ISDETECTING TEXT("IsDetecting")
#define BBKEY_HASROARED TEXT("HasRoared")
#define BBKEY_ATTACKPATTERN1 TEXT("AttackPattern1")
#define BBKEY_ATTACKPATTERN2 TEXT("AttackPattern2")
#define BBKEY_ATTACKPATTERN3 TEXT("AttackPattern3")
#define BBKEY_ATTACKPATTERN4 TEXT("AttackPattern4")
#define BBKEY_ATTACKPATTERN5_1 TEXT("AttackPattern5_1")
#define BBKEY_ATTACKPATTERN5_2 TEXT("AttackPattern5_2")
#define BBKEY_ATTACKPATTERN5_3 TEXT("AttackPattern5_3")
#define BBKEY_ATTACKPATTERN6 TEXT("AttackPattern6")
#define BBKEY_ATTACKPATTERN7 TEXT("AttackPattern7")
#define BBKEY_ATTACKPATTERN8 TEXT("AttackPattern8")
#define BBKEY_ATTACKPATTERN9 TEXT("AttackPattern9")
#define BBKEY_ATTACKPATTERNSELECTED TEXT("AttackPatternSelected")
#define BBKEY_ISANGER TEXT("IsAnger")
#define BBKEY_HASANGERED TEXT("HasAngered")
#define BBKEY_HAVETOESCAPE TEXT("HaveToEscape")
#define BBKEY_HASESCAPED TEXT("HasEscaped")
#define BBKEY_HASESCAPEROARED TEXT("HasEscapeRoared")
#define BBKEY_ESCAPEPOS TEXT("EscapePos")
#define BBKEY_DESTINATIONCOUNT TEXT("DestinationCount")
#define BBKEY_POS TEXT("TrgtPos")
#define BBKEY_PREESCAPEPOS TEXT("PreEscapePos")